include:
  - board: ergohaven
    shield: op36_left
    keymap: op36_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: op36_left_ruen-ergohaven-zmk

  - board: ergohaven
    shield: op36_right

  - board: ergohaven
    shield: settings_reset
